nelmio_api_doc:
    documentation:
        info:
            title: Computer Books API
            description: Documentation for Computer Books API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    html_config:
        assets_mode: 'bundle'
