nelmio_api_doc:
    documentation:
        info:
            title: Computer Books API
            description: Documentation for Computer Books API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                TokenDto:
                    type: object
                    properties:
                        token: { type: string }
                        refresh_token: { type: string }
        security:
            - Bearer: []
        paths:
            '/api/v1/auth/refresh':
                post:
                    tags:
                        - Auth
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        refresh_token:
                                            type: string
                    responses:
                        '200':
                            description: Get New Token and Refresh Token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/TokenDto'
            '/api/v1/auth/login':
                post:
                    tags:
                        - Auth
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Get New Token and Refresh Token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/TokenDto'

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    html_config:
        assets_mode: 'bundle'
