services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: 'wiremock'
    ports:
        - "8080:8080"
    volumes:
        - ./wiremock/mappings:/home/wiremock/mappings
    networks:
      - sfbooks-network
